### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by killer-m** [07151129/sh3proxy#1]
**Shadows resolution:**
0048B1B6
0048B1BB
0048D891
0048D89B
0048D8A5
0048D8AF
0048D8B9
0048D8C3
0048D8CD
0048D8D7

**FPS fluctation fix:**
005F15E2
E8 69 9C E2 FF => E8 A9 0D E1 FF

**FPS Unlock:**
0041992D
E8 8E 19 00 00 => E8 BA 1C 00 00
Disabling FPS limiter is better way to avoid FPS fluctation.
Should be used only with Vsync 60Hz, or external FPS limiter to 60 FPS, since game speed designed for 60 FPS.

**Windows 10 white border fix:**
00403042
68 00 03 00 00 => 68 00 00 00 00

**Comment by CHNSK** [comment]
Can FPS fluctuation be really fixed? I'd be grateful eternally.

**Comment by 07151129** [comment]
@killer-m Thank you for the patches! I will be working on integrating them.

Here are some results of my testing (I will be updating this message):

> FPS fluctation fix:
> 005F15E2
> E8 69 9C E2 FF => E8 A9 0D E1 FF

While this does fix the fluctuation, it limits in-game framerate to 30. It also seems to make game's clock tick two times less frequently. I will try this in conjunction with your FPS unlock patch…

> FPS Unlock:
> 0041992D
> E8 8E 19 00 00 => E8 BA 1C 00 00

This does not seem to disable FPS limit: it still is 60 on my machine. It does disable game clock adjust (the engine seems to be trying to account for framerate drops), so when FPS is less than 60, objects move rather slowly.

In conjunction, your two patches do fix the jitter, but game clock adjust is broken.

I suspect the framerate jitter is related to the renderer itself being suboptimal, so it is going to be a lot harder to fix.

> Shadows resolution:
> 0048B1B6
> 0048B1BB
> 0048D891
> 0048D89B
> 0048D8A5
> 0048D8AF
> 0048D8B9
> 0048D8C3
> 0048D8CD
> 0048D8D7

This works, but also breaks rendering in some scenes (e.g. cafe in the mall). The shadow maps are not present in texture dump, so they're probably freed along the way.

**Comment by killer-m** [comment]
> While this does fix the fluctuation, it limits in-game framerate to 30. It also seems to make game's clock tick two times less frequently.

Very strange, try to lower rendering resolution, to 512x512.

> This does not seem to disable FPS limit: it still is 60 on my machine. It does disable game clock adjust (the engine seems to be trying to account for framerate drops), so when FPS is less than 60, objects move rather slowly.

Looks like, Vsync limit FPS to 60 for you.
For me, it fully unlock FPS - http://funkyimg.com/i/2eQrS.jpg

> This works, but also breaks rendering in some scenes (e.g. cafe in the mall). The shadow maps are not present in texture dump, so they're probably freed along the way.

This should fix broken render in some areas.

**Additional for shadows resolution:**
00427235
0042723A
0048B29A
0048B29F
0048B53B
0048B540

0048D661
0048D696
0048D6D7
0048D6EE
0048DB4E
0048DB58
0048DB62
0048DB6C
0048DB76
0048DB80
0048DB8A
0048DB94

**Comment by 07151129** [comment]
> > This works, but also breaks rendering in some scenes (e.g. cafe in the mall). The shadow maps are not present in texture dump, so they're probably freed along the way.
> 
> This should fix broken render in some areas.
> 
> **Additional for shadows resolution:**

This fixes the bug indeed.

Have you verified your FPS unlock and fluctuation fix patches with a low framerate? They seem to break the game when framerate is under 60.

**Comment by killer-m** [comment]
> Have you verified your FPS unlock and fluctuation fix patches with a low framerate? They seem to break the game when framerate is under 60.

It won't work properly with a low FPS. Minimal FPS must be at least 50+.

**Comment by 07151129** [comment]
> It won't work properly with a low FPS. Minimal FPS must be at least 50+.

That's the problem with this patch. Not every user will be able to maintain high FPS.

**Comment by CHNSK** [comment]
In that case what kind of specs, rig one need to achieve stable 60fps gameplay?

**Comment by CHNSK** [comment]
> For me, it fully unlock FPS - http://funkyimg.com/i/2eQrS.jpg

There are certain places where the engine locks the game to 30fps, like nightmare hospital, the town, outdoor portions of the park, anywhere with fog. How many fps you get in those places? Or do you get any slow motions?

**Comment by killer-m** [comment]
> There are certain places where the engine locks the game to 30fps, like nightmare hospital, the town, outdoor portions of the park, anywhere with fog. How many fps you get in those places? Or do you get any slow motions?

FPS very depend on render resolution, lower resolution - higher FPS.
I get solid 60 FPS and no slow motions.
2048x2048:
http://funkyimg.com/i/2eVrC.jpg
http://funkyimg.com/i/2eVrD.jpg
http://funkyimg.com/i/2eVrE.jpg

4096x4096:
http://funkyimg.com/i/2eVrJ.jpg
http://funkyimg.com/i/2eVrK.jpg
http://funkyimg.com/i/2eVrL.jpg
