### ISSUE TITLE
Error 0xc0000142

### ISSUE THREAD

**Issue by Verbo84** [07151129/sh3proxy#10]
Hi. Keep getting an error message with code: 0xc0000142 when I try to launch sh3. 

On Win10 using Visual C++ 2015 x64. Any help, please.

**Comment by 07151129** [comment]
Check whether:
1. this happens if you use a previous release of sh3proxy
2. any dependency of sh3.exe is missing, using http://dependencywalker.com
3. this happens if you use compatibility mode with an older version of windows

**Comment by 07151129** [comment]
(See https://github.com/07151129/sh3proxy/issues/9 for further discussion)
