### ISSUE TITLE
Status screen resolution

### ISSUE THREAD

**Issue by Keith94** [07151129/sh3proxy#11]
A new fix available for this game includes an option for `StatusScreenRes`:
https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/SilentHill3.WidescreenFix/dllmain.cpp#L321

Is that something that can be added to sh3proxy?

**Comment by 07151129** [comment]
I suppose this can be added, along with some other patches like FMV resolution.

**Comment by 07151129** [comment]
I have added preview resolution override from WidescreenFixesPack. Let me know if you would like to have more patches from there; preferably, attach a screenshot to illustrate the desired effect.

I have tried applying the status screen resolution patch but did not see any difference at all (I have not tested it with their dll, however).
