### ISSUE TITLE
Audio desynchronized when using framerate jitter alternative fix.

### ISSUE THREAD

**Issue by ready2rumble** [07151129/sh3proxy#12]
What it says in the title. When I play the game without any fix the sound is perfect but the framerate keeps switching between 60 and 30 like crazy, it's unplayable. Using the 30fps cap from this mod, whenever I start a new game or load a save, I get stuck in the loading screen forever. Using the alternative fix I get 58/59 fps and it plays great, but on cutscenes the voices get completely out of sync.
Also, no matter what I do, I can't get into the in game options menu. Game stops working and I have to Ctrl alt del out of it. (Not a problem with the patch though, it happens in a clean copy of the game)
My pc:

Intel core i7 4771
Gigabyte GTX 970 G1 gaming
16gb Ram
Windows 10

**Comment by Keith94** [comment]
I had the same desync issues, using the methods of hacking the EXE manually (#1). Do you play in windowed or fullscreen mode btw?

The options menu does work, but it actually takes about 15-20 seconds to enter/exit for some reason.

**Comment by ready2rumble** [comment]
Fullscreen.

And thanks for the options menu tip. You're right, it opens after 15 seconds.

**Comment by ready2rumble** [comment]
You Wanna hear the weirdest thing? I just opened the game and now everything works flawlessly. Weird. I literally did nothing.
