### ISSUE TITLE
Vertical FOV

### ISSUE THREAD

**Issue by KindratKnysh** [07151129/sh3proxy#13]
Greetings! First of all, let me thank you for creating such useful utility. And now the question: is it possible to add vertical FOV setting? Because horizontal FOV by itself doesn't fix the aspect ratio properly. Here's what I mean:
http://funkyimg.com/i/2jDQX.jpg - native 4:3
http://funkyimg.com/i/2jDSo.jpg - 16:9, other utility
http://funkyimg.com/i/2jDTd.jpg - 16:9, your utility (FovX = 80)
http://funkyimg.com/i/2jDSZ.jpg - 16:9, your utility (FovX = 90)
http://funkyimg.com/i/2jDTp.jpg - 16:9, your utility (FovX = 100)

**Comment by 07151129** [comment]
The engine is computing the vertical/horizontal FOV based on some hardcoded coefficients, and last I checked 4/3=1.(3) was indeed used there… I will look into this, and see what the formula for the vertical FOV is.

**Comment by KindratKnysh** [comment]
That would be great, thanks.

**Comment by KindratKnysh** [comment]
Just noticed that the game has black vertical borders 5 pixels each, you can see them on screenshots. And it's not only my issue because others have them too. Interesting detail: when you launch game, main menu doesn't have this borders, but when you load game and exit to main menu - borders appear.

**Comment by Zerobinary99** [comment]
It seems to be possible to change both the horizontal and vertical FOV. The fixes [here](http://www.wsgf.org/dr/silent-hill-3) and [here](https://thirteenag.github.io/wfp#sh3) implemented that properly.

**Comment by 07151129** [comment]
@Zerobinary99 Neither of the fixes you mentioned actually let user set arbitrary FOV angle, they just change the hardcoded aspect ratio in game and let it figure out the rest of the values. This is quite different from what sh3proxy tries to do.

**Comment by 07151129** [comment]
Closing this issue for now, since the fix added in 0.8.4 seems to work satisfactorily.
