### ISSUE TITLE
Zooming Stretches the Image

### ISSUE THREAD

**Issue by CHNSK** [07151129/sh3proxy#2]
When you use zoom feature, game stretches the image vertically. 

https://i.imgur.com/26qtT36.jpg

**Comment by 07151129** [comment]
Thanks for reporting. I did not use that feature, so I did not notice the bug when I was testing the FOV fix. I will see what I can do.

**Comment by CHNSK** [comment]
I also don't use it often but since SH3 is very visceral in detail, It's nice to have a close look at the obscure Valtiel sequences and other models like ceremonial robes and hanged models far away in nightmare worlds. I sincerely thank you for your work to make Silent Hill more modern. Cheers!

**Comment by 07151129** [comment]
Fixed in the upcoming release.
