### ISSUE TITLE
Stutter even though FPS indicates solid 60

### ISSUE THREAD

**Issue by MrMeanor** [07151129/sh3proxy#27]
Hello,

Not sure if this will get answered as this patch was made 2 years ago, but I am having a hard time finding a solution (if one exists). 

Issue: I am using the latest release (v0.9.2) and have the "Patch renderer synchronization code to prevent framerate drops" set to: Enable = 1. MSI Afterburner is indicating that I have a solid 60 fps at all times, however, it will randomly "stutter/jitter" and appears to be briefly dropping down to what 30 FPS looks like despite being locked at 60. I notice this the most when turning the camera, but it can happen when running down a straight path (i.e. running through the alley after exiting the restroom in the beginning of the game). 

I have tried combos of vsync enabled/disabled both within the ini and through the Nvidia control panel, but nothing seems to remedy the stutter. 

Any tips would be appreciated, thanks!

GTX 1080
I7 5930k @ 4.5ghz
EVGA X99 Classified 
32GB Corsair Dominator Platinum @ 2800mhz 
Windows 10 Professional (64bit)

**Comment by 07151129** [comment]
MSI Afterburner framerate sampling frequency may not be high enough to detect short framerate drops, which cause jittery animations (see https://github.com/07151129/sh3proxy/wiki/On-FixJitter-and-lag-compensation for more details).
