### ISSUE TITLE
2 Issiues With The New Release

### ISSUE THREAD

**Issue by CHNSK** [07151129/sh3proxy#3]
I can't run the game, like something interfering, disp.ini is empty when I open it, though.

After trying for 20 minutes and lots of clicking I was able to run game twice and I realized render resolution is not saved and reverting back to 512x512.

**Comment by 07151129** [comment]
> I can't run the game, like something interfering, disp.ini is empty when I open it, though.

The game always starts on first attempt for me, not sure how to debug this.

> render resolution is not saved and reverting back to 512x512.

How do you exit the game? It resets disp.ini unless it was exited normally (i.e. via main menu).

**Comment by CHNSK** [comment]
It turns out it was the DPI scaling -under compatibility- preventing the game to run.  Problem solved when I untick it. Sorry, don't remember why I turned that on. It's okay now.  And setting stopped resetting.

**Comment by 07151129** [comment]
I'm glad to hear it's working for you.
