### ISSUE TITLE
SH3 doesn't run on Windows 10

### ISSUE THREAD

**Issue by tykus160** [07151129/sh3proxy#30]
Hi. I've installed SH3 on my Windows 10 machine and unfortunately game starts randomly. It is not related with this fix however, happens also on vanilla game. Sometimes it runs in windowed mode.
Is there a possibility to try to fix it? If you need additional data about my OS or PC components, please ask.
Also CRC32 of my version is `7E6C991C`.

**Comment by 07151129** [comment]
Have you tried any other version of sh3.exe? I do not recall any specific compatibility issues with Windows 10, but I should re-test this.

**Comment by tykus160** [comment]
Welp, that's the retail version from Europe I have. But now I believe I know the problem - it runs smoothly when game options (not from your proxy) are set to default. Unfortunately, game overrides it after every run, so I have to manually reset them every time before launch. But it's not a big issue, as with your fix the game just uses proxy settings.

**Comment by 07151129** [comment]
You could try locking the config file to make the game unable to write it

**Comment by tykus160** [comment]
That wasn't the case actually. I've downloaded exe you're using and now everything works. I recall Microsoft removed support for SecuROM and other tools like that, so I believe that was a case. Anyway, thanks and sorry for bothering!
