### ISSUE TITLE
Latest release is missing .ini file

### ISSUE THREAD

**Issue by Keith94** [07151129/sh3proxy#7]
I noticed the latest release (v0.8) does not have the updated `sh3proxy.ini` attached in the downloads section... you could also add the two files to a .zip archive for better convenience of installing imo.

**Comment by 07151129** [comment]
My bad, it's there now.

I don't think that users will have trouble downloading two files, so I'll keep it this way for now.

**Comment by Keith94** [comment]
Thanks, also should borderless be set to `1` by default? In the commit 179b7f9 you wrote "Make borderless mode off by default" so I wasn't sure.

**Comment by 07151129** [comment]
Thanks for noticing! Looks like I need to review my commits more thoroughly.
